services:
  elasticsearch2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elasticsearch2
    ports:
      - "9202:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elastic/dict:/usr/share/elasticsearch/config/dict:ro

volumes:
  esdata:
