version: "3.8"

services:
  mysql:
    container_name: hourxchange_mysql
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - hourxchange_net

  elasticsearch:
    build: .
    container_name: hourxchange_elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - hourxchange_net

  redis:
    container_name: hourxchange_redis
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - hourxchange_net

  flask:
    container_name: hourxchange_flask
    build:
      context: ./flaskAPI
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./flaskAPI:/app
    depends_on:
      - redis
      - elasticsearch
    networks:
      - hourxchange_net

networks:
  hourxchange_net:

volumes:
  mysql_data:
  esdata:
