name: Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Node.js dependencies
        working-directory: client-app
        run: npm ci

      - name: Run Prettier
        working-directory: client-app
        run: npx prettier -w "**/*.html" "**/*.js" "**/*.css"

      - name: Run Spotless
        working-directory: backend
        run: ./gradlew spotlessApply
