name: Format Check

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Node.js dependencies
        working-directory: client-app
        run: npm ci

      - name: Run Prettier check
        working-directory: client-app
        run: npx prettier --check "**/*.html" "**/*.js" "**/*.css"

      - name: Grant execute permission for gradlew
        working-directory: backend
        run: chmod +x gradlew

      - name: Run Spotless check
        working-directory: backend
        run: ./gradlew spotlessCheck
